// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "v1.4.3-379-g6c9faa0"
#define MICROPY_GIT_HASH "6c9faa0"
#define MICROPY_BUILD_DATE "2019-03-01"
#define MICROPY_VERSION_MAJOR (1)
#define MICROPY_VERSION_MINOR (4)
#define MICROPY_VERSION_MICRO (3)
#define MICROPY_VERSION_STRING "1.4.3"
