    { MP_OBJ_NEW_QSTR(MP_QSTR_AF1_TIM1),   MP_OBJ_NEW_SMALL_INT(GPIO_AF1_TIM1) },
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF1_TIM2),   MP_OBJ_NEW_SMALL_INT(GPIO_AF1_TIM2) },
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF2_TIM3),   MP_OBJ_NEW_SMALL_INT(GPIO_AF2_TIM3) },
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF2_TIM4),   MP_OBJ_NEW_SMALL_INT(GPIO_AF2_TIM4) },
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF2_TIM5),   MP_OBJ_NEW_SMALL_INT(GPIO_AF2_TIM5) },
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF3_TIM10),  MP_OBJ_NEW_SMALL_INT(GPIO_AF3_TIM10) },
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF3_TIM11),  MP_OBJ_NEW_SMALL_INT(GPIO_AF3_TIM11) },
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF3_TIM9),   MP_OBJ_NEW_SMALL_INT(GPIO_AF3_TIM9) },
#if defined(MICROPY_HW_I2C1_SCL)
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF4_I2C1),   MP_OBJ_NEW_SMALL_INT(GPIO_AF4_I2C1) },
#endif
#if defined(MICROPY_HW_I2C2_SCL)
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF4_I2C2),   MP_OBJ_NEW_SMALL_INT(GPIO_AF4_I2C2) },
#endif
#if defined(MICROPY_HW_I2C3_SCL)
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF4_I2C3),   MP_OBJ_NEW_SMALL_INT(GPIO_AF4_I2C3) },
#endif
#if (defined(MICROPY_HW_ENABLE_I2S2) && MICROPY_HW_ENABLE_I2S2)
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF5_I2S2),   MP_OBJ_NEW_SMALL_INT(GPIO_AF5_I2S2) },
#endif
#if (defined(MICROPY_HW_ENABLE_I2S3) && MICROPY_HW_ENABLE_I2S3)
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF5_I2S3),   MP_OBJ_NEW_SMALL_INT(GPIO_AF5_I2S3) },
#endif
#if (defined(MICROPY_HW_ENABLE_SPI1) && MICROPY_HW_ENABLE_SPI1)
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF5_SPI1),   MP_OBJ_NEW_SMALL_INT(GPIO_AF5_SPI1) },
#endif
#if (defined(MICROPY_HW_ENABLE_SPI2) && MICROPY_HW_ENABLE_SPI2)
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF5_SPI2),   MP_OBJ_NEW_SMALL_INT(GPIO_AF5_SPI2) },
#endif
#if (defined(MICROPY_HW_ENABLE_I2S2) && MICROPY_HW_ENABLE_I2S2)
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF6_I2S2),   MP_OBJ_NEW_SMALL_INT(GPIO_AF6_I2S2) },
#endif
#if (defined(MICROPY_HW_ENABLE_I2S3) && MICROPY_HW_ENABLE_I2S3)
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF6_I2S3),   MP_OBJ_NEW_SMALL_INT(GPIO_AF6_I2S3) },
#endif
#if (defined(MICROPY_HW_ENABLE_SPI3) && MICROPY_HW_ENABLE_SPI3)
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF6_SPI3),   MP_OBJ_NEW_SMALL_INT(GPIO_AF6_SPI3) },
#endif
#if (defined(MICROPY_HW_ENABLE_I2S3) && MICROPY_HW_ENABLE_I2S3)
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF7_I2S3),   MP_OBJ_NEW_SMALL_INT(GPIO_AF7_I2S3) },
#endif
#if defined(MICROPY_HW_UART1_PORT) || defined(MICROPY_HW_UART1_TX_PORT)
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF7_USART1), MP_OBJ_NEW_SMALL_INT(GPIO_AF7_USART1) },
#endif
#if defined(MICROPY_HW_UART2_PORT)
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF7_USART2), MP_OBJ_NEW_SMALL_INT(GPIO_AF7_USART2) },
#endif
#if defined(MICROPY_HW_UART6_PORT)
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF8_USART6), MP_OBJ_NEW_SMALL_INT(GPIO_AF8_USART6) },
#endif
#if defined(MICROPY_HW_I2C3_SCL)
    { MP_OBJ_NEW_QSTR(MP_QSTR_AF9_I2C3),   MP_OBJ_NEW_SMALL_INT(GPIO_AF9_I2C3) },
#endif
